### ISSUE TITLE
Batch Opener

### ISSUE THREAD

**Issue by ross-pure** [renproject/mpc#10]
The current Opener only opens one sharing at a time. However, some protocols, such as RNG, will want to process batches of sharings at a time, so we should upgrade the Opener to be able to open batches of sharings so that it can be used in these contexts.

### Batch Processing Philosophy

When receiving multiple shares at once, we now have the possibility that some of the shares are valid and others are not. In this case it is theoretically possible to make progress in those batches for which the shares are valid, while not doing so for the batches corresponding to the invalid shares. However, initially we should simply consider validity at a collective level: if one of the shares in any of the batches is invalid, we will treat the state transition as the failure case and not add any of the shares, even the valid ones. The reasons for this are:

- Under the security assumptions, this should not change whether or not an open will eventually be completed successfully.
- This makes the logic much simpler and therefore less error prone.

We can change the approach later if we find it necessary/useful to make progress on a per batch basis.

### Outline of Changes Required

The following is a rough outline of the changes that will need to be made to the state machine.

#### State

The state machine will need to be aware of the batch size `b`. This can be considered fixed and given at construction time. Additionally, the other state will of course need to be changed to accommodate the fact that there is more than one sharing now: the `commitment` field will now need to be a list of `Commitment`s and the `shareBuffer` field will now need to be a list of `Shares`. This will in turn require that the `secret` field is also a list.

#### Transitioning on Shares

The `TransitionShare` will now need to receive a list of shares based on the batch size. This also introduces new validity checks that need to be made:

- The list of shares received needs to have length equal to the batch size for the state machine.
- Each share has the same index.

Note that in the current case of a single share, the return value of `TransitionShare` is enough to precisely characterise the nature of the error, if there is any. However, in the batched case this would not be able to tell us which of the shares were invalid. We won't worry about this at the moment, as the caller will still have enough information to identify exactly who behaved maliciously (by e.g. simply iterating through the list of shares and checking for themselves which ones are the culprits). However, we can change the interface at a later date to give more accurate information.

#### Transitioning on Commitments (Reset)

We will also require consistency among the given list of commitments for a reset transition; each commitment should have the same `k` (reconstruction threshold) value. Again this is for simplicity and can be made more flexible at a later date if desired.

### Tests

Naturally, some changes will also need to be made to the tests. The main ones are:

- Randomising over the number of batches
- In tests that currently test behaviour on receiving an invalid share, this now needs to be replaced with an invalid list of shares. This invalid list of shares must have at least one invalid share but the number of invalid shares should be otherwise random.

### Tasks

Given the above, the following tasks should be completed:

- [x] Adjust the state variables of the state machine to be able to handle batches
- [x] Update the transition functions to have the correct interfaces and perform the new validity checks
- [x] Update any auxiliary methods for the state machine as required
- [x] Update any documentation that becomes outdated due to the changes
- [x] Update the tests to adhere to the new changes and add any new test cases that are needed to keep the current code and logical coverage
